# Generated by Django 5.2.5 on 2025-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('telefono', models.PositiveIntegerField(blank=True)),
                ('descripcion', models.TextField(blank=True, max_length=120)),
                ('producto_ref', models.ImageField(upload_to='')),
                ('recibido_de', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
