# Generated by Django 5.2.5 on 2025-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=120)),
                ('tipo_insumo', models.CharField(max_length=120)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('marca_insumo', models.CharField(max_length=120)),
                ('color_insumo', models.CharField(max_length=50)),
            ],
        ),
    ]
