# Generated by Django 5.2.5 on 2025-12-01 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=120),
        ),
    ]
