# Generated by Django 5.2.5 on 2025-12-02 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado_pago',
            field=models.CharField(choices=[('PEN', 'PENDIENTE'), ('PAR', 'PARCIAL'), ('PAG', 'PAGADO')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='estado_seguimiento',
            field=models.CharField(choices=[('SOL', 'SOLICITADO'), ('APR', 'APROBADO'), ('EN', 'EN PROCESO'), ('REA', 'REALIZADO'), ('FIN', 'FINALIZADO'), ('ENT', 'ENTREGADO')], default='SOL', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='producto_ref',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
