# Generated by Django 5.2.5 on 2025-12-02 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_pedidos_estado_pago_pedidos_estado_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
