# Generated by Django 5.2.5 on 2025-12-02 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_pedidos_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=120, unique=True),
        ),
    ]
