# Generated by Django 5.2.5 on 2025-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_add_token_to_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='producto_ref',
            field=models.ImageField(upload_to='pedido_images/'),
        ),
    ]
