# Generated by Django 5.2.5 on 2025-12-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_alter_pedidos_token'),
        ('online', '0006_pedidos_estado_pedidos_fecha_creacion_and_more'),
    ]

    operations = [
    ]
