# Generated by Django 5.2.5 on 2025-12-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_merge_20251202_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='estado_pago',
            new_name='estado_de_pago',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='estado_seguimiento',
            new_name='estado_de_seguimiento',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_creacion',
        ),
    ]
